ens_job:
    path:     /
    defaults: { _controller: "EnsJulesBundle:Job:index" }
    methods:  GET

ens_job_show:
    path:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsJulesBundle:Job:show" }
    requirements:
        id:  \d+
#
#ens_job_preview:
#    path:  /{company}/{location}/{token}/{position}
#    defaults: { _controller: "EnsJulesBundle:Job:preview" }
#    requirements:
#        token:  \w+

ens_job_new:
    path:     /new
    defaults: { _controller: "EnsJulesBundle:Job:new" }
    methods:  [GET, POST]

ens_job_create:
    path:  /create
    defaults: { _controller: "EnsJulesBundle:Job:create" }
    methods:  POST

ens_job_edit:
    path:  /{token}/edit
    defaults: { _controller: "EnsJulesBundle:Job:edit" }

ens_job_update:
    path:  /{token}/update
    defaults: { _controller: "EnsJulesBundle:Job:update" }
    methods:  POST

ens_job_delete:
    path:  /{token}/delete
    defaults: { _controller: "EnsJulesBundle:Job:delete" }
    methods:  POST

ens_job_publish:
    path:  /{token}/publish
    defaults: { _controller: "EnsJulesBundle:Job:publish" }
    methods:  POST

ens_job_extend:
    path:  /{token}/extend
    defaults: { _controller: "EnsJulesBundle:Job:extend" }
    methods:  POST